
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_temperature
      - type: memory_use_percent

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
  
alarm_control_panel:
  - platform: manual
